// Code generated by github.com/citradigital/toldata. DO NOT EDIT.
// package: copyfto
// source: copyfto.proto
package copyfto



import (
	"io"
	"github.com/citradigital/toldata"
	context "golang.org/x/net/context"
)

// Workaround for template problem
func _eof_grpc() error {
	return io.EOF
}



type CopyftoGRPC struct {
	Context context.Context
	Bus     *toldata.Bus
	Service *CopyftoToldataClient
}

func NewCopyftoGRPC(ctx context.Context, config toldata.ServiceConfiguration) (*CopyftoGRPC, error) {
	

	service := CopyftoGRPC{
		Context: ctx,
	
		Service: NewCopyftoToldataClient(nil),
	
	}

	return &service, nil
}

func (svc *CopyftoGRPC) Close() {
	svc.Bus.Close()
}

	




func (svc *CopyftoGRPC) CopyFileDummyOrder(ctx context.Context, req *Empty) (*GenericReponse, error) {
	return svc.Service.CopyFileDummyOrder(ctx, req)
}




